#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

# Standard Community Cookbooks 
cookbook 'apt'  
cookbook 'ntp'
cookbook 'java'
cookbook 'nginx'
cookbook 'git'
cookbook 'subversion'
cookbook 'memcached'
cookbook 'aws'
cookbook 'elasticsearch'

# Cloned and Patched Community Cookbooks
cookbook 'postgresql',
	:path => '../cloned-cookbooks/postgresql/'
cookbook 'database',
	:path => '../cloned-cookbooks/database/'
cookbook 'tomcat', # eventuell 7er
	:path => '../cloned-cookbooks/tomcat/'

# Not yet published cookbooks available via git
cookbook 'application_java',
	:git => 'https://github.com/opscode-cookbooks/application_java.git'
cookbook 'application',
	:git => 'https://github.com/opscode-cookbooks/application.git'
cookbook 'vagrant-ohai',
	:git => 'https://github.com/tknerr/vagrant-ohai.git'



# cookbook 'ruby' # 1.9er


